# Generated by Django 3.0 on 2021-01-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plants',
            old_name='image_name',
            new_name='image_field',
        ),
    ]
